.TH simple_shell.sh 1
.SH NAME
simple_shell.sh \- Displays a prompt and wait for the user to type a command.
.SH SYNOPSIS
.B simple_shell.sh
[ Simple shell 0.1 + ]
[ Simple shell 0.2 + ]
[ Simple shell 0.3 + ]
[ Simple shell 0.4 + ]
.SH DESCRIPTION
.B simple_shell.sh
This script does the following. It prints the results if a condition is met.
.SH OPTIONS
.TP
.BR Simple shell 0.1 +
Handles command lines with arguments
.TP
.BR Simple shell 0.2 +
Handle the PATH
fork must not be called if the command doesn’t exist
.TP
.BR Simple shell 0.3 +
Implement the exit built-in, that exits the shell
Usage: exit
You don’t have to handle any argument to the built-in exit
.TP
.BR Simple shell 0.4 +
Implement the env built-in, that prints the current environment		
